### ISSUE TITLE
Features / ToDo

### ISSUE THREAD

**Issue by mrabe89** [mrabe89/kissmyconfig#1]
- [ ] Verify Owner / Permissions as file state
- [ ] Only copy files, that need to be updated
- [ ] task ARGs via CLI
- [ ] link tasks by dependencies (with ARGs)
- [ ] better macro tag (not (($ )
- [ ] use ENV_VARs as task ARGs
- [ ] rescue/ensure on tasks
- [ ] finer include - allow overwriting of subtasks
- [ ] task tests - verify success (e.g. Port 80 answers(apache))
- [ ] copy directories
- [ ] print ARGs in 'Do taskname' debug output
- [ ] don't diff on binary files
